#!/bin/sh
#inkVerbSerf! verb.ink
#set -e

# This removes a subdomain A & AAAA records from an existing GURU DNS record in the inkDNS zone file on this Verber

# How to use:
## ./inkdnskillvipsub [subdomain]


DNSSUBDOM=$1

# Include the configs
. /var/local/verb/configs/sitenameip
. /var/local/verb/configs/siteurilist

# Check if already added
if ! grep -Fq "${DNSSUBDOM}.${vipURI}" /var/local/verb/configs/inkdns/zones/${vipURI}.db; then
echo "The subdomain ${DNSSUBDOM} has not been added to ${vipURI}. Use inkdnsaddsub to add it."
exit 0; fi

# Remove the record
sed -i "/; Subdomain Records Added by inkDNS ${DNSSUBDOM}\.${vipURI}/,+2d" /var/local/verb/configs/inkdns/zones/${vipURI}.db

# Set the Serial No
/var/local/verb/serfs/inkdnsserial ${DNSDOMAIN}

# Finish
echo "The GURU subdomain ${DNSSUBDOM} has been removed from the DNS zone file."

