#!/bin/sh
#inkVerbSerf! verb.ink
#set -e

# This adds a subdomain A & AAAA records to an existing GURU DNS record in the inkDNS zone file on this Verber

# How to use:
## ./inkdnsaddvipsub [subdomain]


DNSSUBDOM=$1

# Include the configs
. /var/local/verb/configs/sitenameip
. /var/local/verb/configs/siteurilist

# Check if already added
if grep -Fq "${DNSSUBDOM}.${vipURI}" /var/local/verb/configs/inkdns/zones/${vipURI}.db; then
echo "The subdomain ${DNSSUBDOM} has already been added to ${vipURI}. Use inkdnskillsub to remove it."
exit 0; fi

# Echo the record
echo "; Subdomain Records Added by inkDNS ${DNSSUBDOM}\.${vipURI}" >> /var/local/verb/configs/inkdns/zones/${vipURI}.db
echo "${DNSSUBDOM}\.${vipURI}\tIN  A\t\t${SITEIP}" >> /var/local/verb/configs/inkdns/zones/${vipURI}.db
echo "${DNSSUBDOM}\.${vipURI}\tIN  AAAA\t\t${SITEIPV6}" >> /var/local/verb/configs/inkdns/zones/${vipURI}.db

# Set the Serial No
/var/local/verb/serfs/inkdnsserial ${DNSDOMAIN}

# Finish
echo "The GURU subdomain ${DNSSUBDOM} has been added to the DNS zone file."

