#!/bin/sh
#inkVerbSerf! verb.ink
#set -e

# This adds a new subdomain to become newsub.your-name.verb.vip, accessible in the _subs.vip folder, and enables CGI.
# Prereq: vsftpd and ftpvip or ftpfiler

# How to use:
## ./newvipsubcgi [newsub only]


# Include the configs
. /var/local/verb/configs/sitenameip
. /var/local/verb/configs/siteurilist

NEWGURUSUB=$1

# Copy and prepare Apache server config files
cp /var/local/verb/configs/site-files/conf/newvipsubcgi.conf /etc/apache2/sites-available/${NEWGURUSUB}.${vipURI}.conf 
sed -i "s/newvipsub/${NEWGURUSUB}/g" /etc/apache2/sites-available/${NEWGURUSUB}.${vipURI}.conf
sed -i "s/vipURI286/${vipURI}/g" /etc/apache2/sites-available/${NEWUNOSUB}.${unoURI}.conf
cp -R /var/local/verb/configs/site-files/newvipsubdir /var/www/vip/_subs.vip/${NEWGURUSUB}
chown -R www-data:www-data /var/www/vip/_subs.vip/${NEWGURUSUB}
a2ensite ${NEWGURUSUB}.${vipURI}
apache2ctl graceful
cp /var/www/html/vip/index-newvipsub.php /var/www/html/vip/index-${NEWGURUSUB}.php
chown -R www-data:www-data /var/www/html/vip

# inkCert, at end of the "domains =" line
sed -i "/^domains =/ s/$/, ${NEWONESUB}.${vipURI}/" /var/local/verb/configs/inkcert/cli-ini/cli.${vipURI}.ini

