#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This downloads and updates the Verber™ core files, including serfs and inklists
## If the verbdomain mod is in effect, it will automatically run again at the end of this update
## This also runs scripts that make other changes that may affect the Verber

# How to use:
## ./updateverber


# Download and unpack the latest checked version from the Inkver repo
cd /var/local/verb/
/var/local/verb/serfs/inkget verber.update.current
unzip -q verber.update.current.zip
rm -f verber.update.current.zip

# Run the update script
/var/local/verb/verber.update.current/update

# Remove the entire updater
rm -rf /var/local/verb/verber.update.current

