#!/bin/sh
# $0 is the script name, $1 id the first ARG, $2 is second...

# This prepares the config to permanently change the base of inkVerb from verb.tld to tld.yourdomain.new
## This sets the config file that will also change any updates

# How to use:
## ./setdomainverb [domain]


# Include the config file
. /var/local/verb/configs/sitenameip

NEWDOMAIN=$1

# Prepare the prep configs
echo "#!/bin/sh
DOMAINVERB=${NEWDOMAIN}" > /var/local/verb/configs/sitedomainverber
sed -i "g/VTYPE=VERB_VERBER/VTYPE=DOMAIN_READY/g" /var/local/verb/inklists/verberverno

# Finish
echo "This inkVerb server is now ready to permanently change the site from verb.ink to ${NEWDOMAIN}.
Proceed if you are ready."

