#!/bin/sh
#inkVerbMaker! verb.ink

# This sets the inkNet repo to ink.ink.verb.ink for dev purposes
# How to use:
## ./make-dev-ink


sed -i "s/INKGET_METHOD=.*/INKGET_METHOD=\"USE_WGET\"/" /var/local/verb/configs/siteinkget
sed -i "s/INKGET_REPO=.*/INKGET_REPO=\"ink\.ink\.verb\.ink\"/" /var/local/verb/configs/siteinkget
rm -f make-dev-ink

