#!/bin/sh
#inkVerbMaker! verb.ink

# This makes the initial inkVerb Verber server with a "boss" sudoer user, new SSH login port, the name286 namespace for setupverb
## Prerequisite: Copy the Vubuntu directory contents (verb) to /var/local/
## Prerequisite: make-verber-preserver

# NOTE on MySQL:
## The MySQL root password will be saved to a filename in the inst directory for your reference
## This file is moved to verb/configs by setupverb
## On a healthy Verber server, you will never need the MySQL root password except for special maintanence
## Verber can create other superusers for MySQL with grant privileges for login to PHPMyAdmin
## Should the MySQL root password become necessary it is a headache if lost. Hence, it is saved in this one location and you don't need to keep track of it.

# How to use:
## ./make-verber [swap-size, choose GB: 1, 2, 4, 8, 16, 32, 64]

# Eg:
## ./make-verber 1 mysqlrootpass
## ./make-verber 4 1620 bossy chewcud62 mysqlroot82


# Install pwgen
apt install -y pwgen

SWAPSIZEMAKE=$1
MYSQLPASS=$(pwgen -0 -1 -A -B 11)
MYSQLBOSSPASS=$(pwgen -s -1 10)

# Verify SSH Directory
cd ~
if [ ! -d ~/.ssh ]; then
mkdir .ssh
fi

# Swap
/var/local/verb/serfs/setswapsize ${SWAPSIZEMAKE}

# Snakeoil Cert
apt install -y ssl-cert
make-ssl-cert generate-default-snakeoil --force-overwrite

# Link serfs & tools to boss box
ln -s /var/local/verb/serfs /var/local/verb/boss/
ln -s /var/local/verb/tools /var/local/verb/boss/

# Link setupverb to serfs
ln -s /var/local/verb/inst/setupverb /var/local/verb/serfs/

# Link verb to root home
ln -s /var/local/verb /root/

# Record the MySQL root password
echo "${MYSQLPASS}" > /var/local/verb/inst/mysqlrootpassword

# LAMP Server
apt update
apt upgrade -y
## Set up MySQL password on install before installing LAMP stack
echo "mysql-server mysql-server/root_password password ${MYSQLPASS}" | debconf-set-selections
echo "mysql-server mysql-server/root_password_again password ${MYSQLPASS}" | debconf-set-selections
#apt -y install mysql-server
## Continue with LAMP Server
apt install -y lamp-server^
apt install -y \
  php7.0-mcrypt \
  php7.0-curl \
  php7.0-gd \
  php7.0-mbstring \
  php-apcu \
  php-xml-parser

# MySQL conf for Postfix Admin
echo "##### Added by inkVerb ######
# This removes NO_ZERO_IN_DATE and NO_ZERO_DATE, which cause problems for   
# Postfix Admin code, from strict mode.
sql_mode=ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
##### End inkVerb #####
" >> /etc/mysql/mysql.conf.d/mysqld.cnf
service mysql restart

# Use OpenSSL to create a unique Diffie-Helman Group file (security)
openssl dhparam -out /etc/ssl/private/dhparams.pem 2048
chmod 600 /etc/ssl/private/dhparams.pem

# Apache
cp /var/local/verb/inst/config/etc/apache2/sites-available/000-default.conf /etc/apache2/sites-available/
cp /var/local/verb/inst/config/etc/apache2/sites-available/default-ssl.conf /etc/apache2/sites-available/
cp /var/local/verb/inst/config/etc/apache2/sites-available/* /etc/apache2/sites-available/
cp /var/local/verb/inst/config/etc/apache2/mods-available/ssl.conf /etc/apache2/mods-available/
cp /var/local/verb/inst/config/etc/apache2/conf-available/security.conf /etc/apache2/conf-available/
a2enmod deflate expires headers rewrite ssl && a2ensite 000-default default-ssl && service apache2 restart

#### If the install goes correctly, remove all commented below #########################################################
##### Below is replaced by serfs/updatehtmlverbs #######################################################################
# Web folders
## Create the default folders
#cp -R /var/local/verb/inst/config/html /var/www/
#cp -R /var/local/verb/inst/config/html /var/local/verb/inst/configs/conflab/
## Create the temporary destination html/.. folders
#/var/local/verb/serfs/updatehtmlverbs

#### If the install goes correctly, remove all commented below #########################################################
##### Below is replaced by serfs/updatehtmlverbs #######################################################################
#cd /var/www/html
#mkdir 0ne
#echo "<?php header(\"Location: http://name286.verb.ink\"); die(); ?>" > /var/www/html/0ne/index.php
#cp -R 0ne email
#cp -R 0ne one
#cp -R 0sitedefaultInProgress ink
#cp -R 0ne ink.ask
#cp -R 0ne ink.bb
#cp -R 0ne ink.blog
#cp -R 0ne ink.code
#cp -R 0ne ink.home
#cp -R 0ne ink.pen
#cp -R 0ne ink.shop
#cp -R 0ne ink.sn
#cp -R 0ne ink.wiki
#cp -R 0ne blue
#cp -R 0ne blue.owncloud
#cp -R 0ne blue.pydio
#cp -R 0ne blue.seafile
#cp -R 0ne guru
#cp -R 0ne guru.cgi
#cp -R 0ne guru.ftp
#cp -R 0ne guru.files
#cp -R 0ne guru.fossil
#cp -R 0ne guru.sql
#cp -R 0ne guru.net2ftp
#cp -R 0ne guru.repo
#cp -R 0ne kiwi
#cp -R 0ne kiwi.ampache
#cp -R 0ne kiwi.art
#cp -R 0ne kiwi.gallery
#cp -R 0ne kiwi.media
#cp -R 0ne kiwi.podcast
#cp -R 0ne kiwi.studio
#cp -R 0ne pink
#cp -R 0ne red
#cp -R 0ne red.act
#cp -R 0ne red.crm
#cp -R 0ne red.erp
#cp -R 0ne red.hrm
#cp -R 0ne red.odoo
#cp -R 0ne red.scm
#cp -R 0ne rocks
#cp -R 0ne uno
### Set subdomain pointers
#mkdir email.email
#mkdir one.one
#mkdir ink.ink
#mkdir blue.blue
#mkdir guru.guru
#mkdir kiwi.kiwi
#mkdir red.red
#mkdir rocks.rocks
#mkdir uno.uno
#echo "<?php header(\"HTTP/1.1 301 Moved Permanently\"); header(\"Location: http://name286.verb.email\"); die(); ?>" > /var/www/html/email.email/index.php
#echo "<?php header(\"HTTP/1.1 301 Moved Permanently\"); header(\"Location: http://name286.verb.one\"); die(); ?>" > /var/www/html/one.one/index.php
#echo "<?php header(\"HTTP/1.1 301 Moved Permanently\"); header(\"Location: http://name286.verb.ink\"); die(); ?>" > /var/www/html/ink.ink/index.php
#echo "<?php header(\"HTTP/1.1 301 Moved Permanently\"); header(\"Location: http://name286.verb.blue\"); die(); ?>" > /var/www/html/blue.blue/index.php
#echo "<?php header(\"HTTP/1.1 301 Moved Permanently\"); header(\"Location: http://name286.verb.guru\"); die(); ?>" > /var/www/html/guru.guru/index.php
#echo "<?php header(\"HTTP/1.1 301 Moved Permanently\"); header(\"Location: http://name286.verb.kiwi\"); die(); ?>" > /var/www/html/kiwi.kiwi/index.php
#echo "<?php header(\"HTTP/1.1 301 Moved Permanently\"); header(\"Location: http://name286.verb.red\"); die(); ?>" > /var/www/html/red.red/index.php
#echo "<?php header(\"HTTP/1.1 301 Moved Permanently\"); header(\"Location: http://name286.verb.rocks\"); die(); ?>" > /var/www/html/rocks.rocks/index.php
#echo "<?php header(\"HTTP/1.1 301 Moved Permanently\"); header(\"Location: http://name286.verb.uno\"); die(); ?>" > /var/www/html/uno.uno/index.php
### Create pointink, pointguru, pointone, and pointuno source files
#echo "<?php header(\"Location: http://name286.verb.ink\"); die(); ?>" > /var/www/html/one/index-one.php
#echo "<?php header(\"Location: http://newonesub.name286.verb.one\"); die(); ?>" > /var/www/html/one/index-newonesub.php
#echo "<?php header(\"Location: http://owncloud.name286.verb.blue\"); die(); ?>" > /var/www/html/blue/index-owncloud.php
#echo "<?php header(\"Location: http://pydio.name286.verb.blue\"); die(); ?>" > /var/www/html/blue/index-pydio.php
#echo "<?php header(\"Location: http://seafile.name286.verb.blue\"); die(); ?>" > /var/www/html/blue/index-seafile.php
#echo "<?php header(\"Location: http://name286.verb.blue\"); die(); ?>" > /var/www/html/blue/index-blue.php
#echo "<?php header(\"Location: http://hrm.name286.verb.guru\"); die(); ?>" > /var/www/html/guru/index-guru.php
#echo "<?php header(\"Location: http://newgurusub.name286.verb.guru\"); die(); ?>" > /var/www/html/guru/index-newgurusub.php
#echo "<?php header(\"Location: http://cgi.name286.verb.guru\"); die(); ?>" > /var/www/html/guru/index-cgi.php
#echo "<?php header(\"Location: http://ftp.name286.verb.guru\"); die(); ?>" > /var/www/html/guru/index-ftp.php
#echo "<?php header(\"Location: http://files.name286.verb.guru\"); die(); ?>" > /var/www/html/guru/index-files.php
#echo "<?php header(\"Location: http://fossil.name286.verb.guru\"); die(); ?>" > /var/www/html/guru/index-fossil.php
#echo "<?php header(\"Location: http://sql.name286.verb.guru\"); die(); ?>" > /var/www/html/guru/index-sql.php
#echo "<?php header(\"Location: http://net2ftp.name286.verb.guru\"); die(); ?>" > /var/www/html/guru/index-net2ftp.php
#echo "<?php header(\"Location: http://repo.name286.verb.guru\"); die(); ?>" > /var/www/html/guru/index-repo.php
#echo "<?php header(\"Location: http://ampache.name286.verb.kiwi\"); die(); ?>" > /var/www/html/kiwi/index-ampache.php
#echo "<?php header(\"Location: http://art.name286.verb.kiwi\"); die(); ?>" > /var/www/html/kiwi/index-art.php
#echo "<?php header(\"Location: http://gallery.name286.verb.kiwi\"); die(); ?>" > /var/www/html/kiwi/index-gallery.php
#echo "<?php header(\"Location: http://media.name286.verb.kiwi\"); die(); ?>" > /var/www/html/kiwi/index-media.php
#echo "<?php header(\"Location: http://podcast.name286.verb.kiwi\"); die(); ?>" > /var/www/html/kiwi/index-podcast.php
#echo "<?php header(\"Location: http://studio.name286.verb.kiwi\"); die(); ?>" > /var/www/html/kiwi/index-studio.php
#echo "<?php header(\"Location: http://name286.verb.ink\"); die(); ?>" > /var/www/html/kiwi/index-kiwi.php
#echo "<?php header(\"Location: http://act.name286.verb.red\"); die(); ?>" > /var/www/html/red/index-act.php
#echo "<?php header(\"Location: http://crm.name286.verb.red\"); die(); ?>" > /var/www/html/red/index-crm.php
#echo "<?php header(\"Location: http://erp.name286.verb.red\"); die(); ?>" > /var/www/html/red/index-erp.php
#echo "<?php header(\"Location: http://hrm.name286.verb.red\"); die(); ?>" > /var/www/html/red/index-hrm.php
#echo "<?php header(\"Location: http://odoo.name286.verb.red\"); die(); ?>" > /var/www/html/red/index-odoo.php
#echo "<?php header(\"Location: http://scm.name286.verb.red\"); die(); ?>" > /var/www/html/red/index-scm.php
#echo "<?php header(\"Location: http://name286.verb.ink\"); die(); ?>" > /var/www/html/red/index-red.php
#echo "<?php header(\"Location: http://name286.verb.ink\"); die(); ?>" > /var/www/html/rocks/index-rocks.php
#echo "<?php header(\"Location: http://name286.verb.ink\"); die(); ?>" > /var/www/html/uno/index-uno.php
#echo "<?php header(\"Location: http://newunosub.name286.verb.uno\"); die(); ?>" > /var/www/html/uno/index-newunosub.php
########################################################################################################################
## Create vsftp web mod directories for guru
mkdir /srv/guru
mkdir /srv/guru/_domains
mkdir /srv/guru/_filecabinet
mkdir /srv/guru/filers
mkdir /srv/guru/files
mkdir /srv/guru/repo
mkdir /srv/guru/_webapps
mkdir /srv/guru/_subs.guru
ln -s /srv/guru /var/www/
ln -s /srv/guru /var/local/verb/boss/
## And the domains directory for hosted domains
mkdir /var/www/domains
## Create inkVerb app directories
mkdir /var/www/email
mkdir /var/www/one
mkdir /var/www/uno
mkdir /var/www/vapps
## Own everything
chown -R www-data:www-data /var/www
chown -R www-data:www-data /srv/guru
service apache2 restart

# Blacklist OpenSSL recommended package
apt install -y openssl-blacklist

# Memcached
apt install -y memcached
## Set memory allocation higher than 64M for heavier servers IF YOU WANT, such as 256
#nano /etc/memcached.conf
#.
#-m 256

##### What was this doing on the alpha server!? #######
########## EVEN IF needed, should use a2enmod, NEVER link directly
########## Besides, this is php7 and may not even be necessary, could relate to using inkCert/Letsencrypt, a jesse/ink discrepancy at the 16 update
### Finish php5-imap link
#ln -sf ../../mods-available/imap.ini /etc/php5/apache2/conf.d/20-imap.ini
#service apache2 restart
#########################################################


# MySQL superuser to auto-create databases
mysql -uroot -p${MYSQLPASS} -e "
CREATE USER mysqlboss@localhost;
SET PASSWORD FOR mysqlboss@localhost=PASSWORD('${MYSQLBOSSPASS}');
GRANT ALL PRIVILEGES ON *.* TO 'mysqlboss'@'localhost' IDENTIFIED BY '${MYSQLBOSSPASS}' WITH GRANT OPTION;
FLUSH PRIVILEGES;"
## Set the mysqlboss as the mysqlboss config file so the password is not in the line command
echo "[client]
user = mysqlboss
password = ${MYSQLBOSSPASS}
host = localhost" > /var/local/verb/inst/mysqlboss.cnf

# Local Apps (prep, not installed)
## Install several tools necessary for Nextcloud
apt install php-bz2 php-curl php-gd php-imagick php-intl php-mbstring php-xml php-zip
## Install curl to download Ghost and for repo update Donjon Knights
apt install curl
## Enable port proxy mods for Ghost sites
a2enmod proxy_http
## Create directory for Ghost installs
mkdir /var/local/ghost

# PHP mods
phpenmod mcrypt

# Monit
apt install -y monit
## Copy configs (These seem to have precedence, files in /etc/monit seem to conflict with them but may be used instead
mkdir /etc/monit/monitrc.d
cp /var/local/verb/inst/config/etc/monit/monitrc.d/acpid /etc/monit/monitrc.d/
cp /var/local/verb/inst/config/etc/monit/monitrc.d/apache2 /etc/monit/monitrc.d/
cp /var/local/verb/inst/config/etc/monit/monitrc.d/memcached /etc/monit/monitrc.d/
cp /var/local/verb/inst/config/etc/monit/monitrc.d/mysql /etc/monit/monitrc.d/
cp /var/local/verb/inst/config/etc/monit/monitrc.d/openssh-server /etc/monit/monitrc.d/
cp /var/local/verb/inst/config/etc/monit/monitrc.d/sshd /etc/monit/monitrc.d/
service monit restart

# Host names
## Set /etc/hostname
echo "host286.name286.verb.tld286" > /etc/hostname
## Set /etc/hosts
sed -i "s/127\.0\.1\.1.*/127\.0\.1\.1 host286.name286.verb.tld286 host286/g" /etc/hosts
sed -i "s/127\.0\.0\.1.*/127\.0\.0\.1 host286.name286.verb.tld286 localhost/g" /etc/hosts

# Delete the Diffie-Helman Group security file to prevent security risks
rm -f /etc/ssl/private/dhparams.pem

# Delete the snakeoil pair to prevent security risks
rm -f /etc/ssl/certs/ssl-cert-snakeoil.pem
rm -f /etc/ssl/private/ssl-cert-snakeoil.key

# Restart Server and reconnect at the new port
echo "
The Verber™ server has been made and is ready to run setupverb.

At this point, there is no urgent need to restart the server.
"

# Delete this one-time script
rm /var/local/verb/serfs/make-verber
rm /var/local/verb/inst/make-verber


