#!/bin/sh
#inkVerbMaker! verb.ink

# This makes the initial inkVerb Verber server with a "boss" sudoer user, new SSH login port, the name286 namespace for setupverb
## Prerequisite: Copy the Vubuntu directory contents (verb) to /var/local/
## Prerequisite: make-verber-preserver

# NOTE on MySQL:
## The MySQL root password will be saved to a filename in the inst directory for your reference
## This file is moved to verb/configs by setupverb
## On a healthy Verber server, you will never need the MySQL root password except for special maintanence
## Verber can create other superusers for MySQL with grant privileges for login to PHPMyAdmin
## Should the MySQL root password become necessary it is a headache if lost. Hence, it is saved in this one location and you don't need to keep track of it.

# How to use:
## ./make-verber [swap-size, choose GB: 1, 2, 4, 8, 16, 32, 64 - optional (2 default, must be set for root password)] [mysql root password - optional]

# Eg:
## ./make-verber 1 mysqlrootpass
## ./make-verber 4
## ./make-verber 2 chewcud62


# Good housekeeping
chmod 750 /opt/verb/serfs/*

# Install in small groups to avoid breaking

# Install pwgen
apt install -y pwgen

# Install zip
apt install -y zip unzip

# Install tools
apt install -y rename htop

if [ -z "$1" ]; then
SWAPSIZEMAKE="4"
MYSQLPASS=$(pwgen -0 -1 -A -B 11)
else
SWAPSIZEMAKE=$1
MYSQLBOSSPASS=$(pwgen -s -1 10)
 if [ -z "$2" ]; then
 MYSQLPASS=$(pwgen -0 -1 -A -B 11)
 else
 MYSQLPASS=$2
 fi
fi

# Verify SSH Directory
cd ~
if [ ! -d ~/.ssh ]; then
mkdir .ssh
fi

# Swap
/opt/verb/serfs/setswapsize ${SWAPSIZEMAKE}; wait
## Enable swap at next startup
echo "/var/swap.img    none    swap    sw    0    0" >> /etc/fstab

# Snakeoil install
apt install -y ssl-cert

# Link serfs & tools to boss box
ln -sfn /opt/verb/serfs /opt/verb/boss/
ln -sfn /opt/verb/tools /opt/verb/boss/

# Link setupverb to serfs
ln -sfn /opt/verb/inst/setupverb /opt/verb/serfs/

# Link verb to root home
ln -sfn /opt/verb /root/

# Record the MySQL root password
echo "${MYSQLPASS}" > /opt/verb/inst/mysqlrootpassword

# LAMP Server
apt update
apt upgrade -y
dpkg --configure -a
apt autoremove -y
## Set up MySQL password on install before installing LAMP stack
echo "mysql-server mysql-server/root_password password ${MYSQLPASS}" | debconf-set-selections
echo "mysql-server mysql-server/root_password_again password ${MYSQLPASS}" | debconf-set-selections
#apt -y install mysql-server
## Continue with LAMP Server
apt install -y lamp-server^
## Get mcrypt to work as of PHP 7.2
apt install -y php-dev gcc make autoconf libc-dev pkg-config
####### mcrypt suspended for testing ###
#apt install -y \
#  libmcrypt-dev \
#  libreadline-dev
#### Skip the pecl prompt with a new line
#printf "\n" | pecl install mcrypt-1.0.1
####### mcrypt ##########################
## PHP extras
apt install -y \
  php-curl \
  php-gd \
  php-mbstring \
  php-apcu \
  php-xml

# MySQL conf for Postfix Admin
echo "##### Added by inkVerb ######
# This removes NO_ZERO_IN_DATE and NO_ZERO_DATE, which cause problems for   
# Postfix Admin code, from strict mode.
sql_mode=ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
##### End inkVerb #####
" >> /etc/mysql/mysql.conf.d/mysqld.cnf
service mysql restart

# Stop using this to see how everything works
# Use OpenSSL to create a unique Diffie-Helman Group file (security)
#openssl dhparam -out /etc/ssl/private/dhparams.pem 2048
#Bug? This is only temporary anyway
#chmod 600 /etc/ssl/private/dhparams.pem

# Apache
cp /opt/verb/inst/root-config/etc/apache2/sites-available/000-default.conf /etc/apache2/sites-available/
cp /opt/verb/inst/root-config/etc/apache2/sites-available/default-ssl.conf /etc/apache2/sites-available/
cp /opt/verb/inst/root-config/etc/apache2/sites-available/* /etc/apache2/sites-available/
cp /opt/verb/inst/root-config/etc/apache2/mods-available/ssl.conf /etc/apache2/mods-available/
cp /opt/verb/inst/root-config/etc/apache2/conf-available/security.conf /etc/apache2/conf-available/
cp -r /opt/verb/inst/conf/lab/html/0sitedefaultInProgress /var/www/html/
cp -r /opt/verb/inst/conf/lab/html/0sitedefaultInProgress /var/www/html/vsslsitedefault
a2enmod deflate expires headers rewrite ssl && a2ensite 000-default default-ssl && apache2ctl graceful

## Create vip & vsftp web mod directories
mkdir /srv/vip
mkdir /srv/vip/_domains
mkdir /srv/vip/_filecabinet
mkdir /srv/vip/filers
mkdir /srv/vip/files
mkdir /srv/vip/repo
mkdir /srv/vip/_webapps
mkdir /srv/vip/_subs.vip
ln -sfn /srv/vip /var/www/
ln -sfn /srv/vip /opt/verb/boss/
ln -sfn /srv/vip /root/
## And the domains directory for hosted domains
mkdir /var/www/domains
## Create inkVerb app directories
mkdir /var/www/email
mkdir /var/www/one
mkdir /var/www/vapps
## Own everything
chown -R www-data:www-data /var/www
chown -R www-data:www-data /srv/vip
apache2ctl graceful

# inkGet repo
mkdir -p /opt/verb/repo

# Blacklist OpenSSL recommended package
# Package not found
#apt install -y openssl-blacklist

# Memcached
apt install -y memcached
## Set memory allocation higher than 64M for heavier servers IF YOU WANT, such as 256
#nano /etc/memcached.conf
#.
#-m 256

##### What was this doing on the alpha server!? #######
########## EVEN IF needed, should use a2enmod, NEVER link directly
########## Besides, this is php7 and may not even be necessary, could relate to using inkCert/Letsencrypt, a jesse/ink discrepancy at the 16 update
### Finish php5-imap link
#ln -sf ../../mods-available/imap.ini /etc/php5/apache2/conf.d/20-imap.ini
#apache2ctl graceful
#########################################################

# MySQL superuser to auto-create databases
mysql -uroot -p${MYSQLPASS} -e "
CREATE USER mysqlboss@localhost;
SET PASSWORD FOR mysqlboss@localhost=PASSWORD('${MYSQLBOSSPASS}');
GRANT ALL PRIVILEGES ON *.* TO 'mysqlboss'@'localhost' IDENTIFIED BY '${MYSQLBOSSPASS}' WITH GRANT OPTION;
FLUSH PRIVILEGES;"
## Set the mysqlboss as the mysqlboss config file so the password is not in the line command
echo "[client]
user = mysqlboss
password = ${MYSQLBOSSPASS}
host = localhost" > /opt/verb/inst/mysqlboss.cnf

# Local Apps (prep, not installed)
## Install several tools necessary for Nextcloud
apt install -y php-bz2 php-curl php-gd php-imagick php-intl php-mbstring php-xml php-zip
## Install curl to download Ghost and for repo update Donjon Knights
apt install -y curl
## Enable port proxy mods for Ghost sites
a2enmod proxy_http
## Create directory for Ghost installs
mkdir /var/www/ghost

# PHP mods
#phpenmod mcrypt

# Monit
apt install -y monit
## Copy configs (These seem to have precedence, files in /etc/monit seem to conflict with them but may be used instead
mkdir /etc/monit/monitrc.d
cp /opt/verb/inst/root-config/etc/monit/monitrc.d/acpid /etc/monit/monitrc.d/
cp /opt/verb/inst/root-config/etc/monit/monitrc.d/apache2 /etc/monit/monitrc.d/
cp /opt/verb/inst/root-config/etc/monit/monitrc.d/memcached /etc/monit/monitrc.d/
cp /opt/verb/inst/root-config/etc/monit/monitrc.d/mysql /etc/monit/monitrc.d/
cp /opt/verb/inst/root-config/etc/monit/monitrc.d/openssh-server /etc/monit/monitrc.d/
cp /opt/verb/inst/root-config/etc/monit/monitrc.d/sshd /etc/monit/monitrc.d/
systemctl reload monit

# Delete the Diffie-Helman Group security file to prevent security risks (keep this verber unique)
rm -f /etc/ssl/private/dhparams.pem

# Delete the snakeoil pair to prevent security risks (keep this verber unique)
rm -f /etc/ssl/certs/ssl-cert-snakeoil.pem
rm -f /etc/ssl/private/ssl-cert-snakeoil.key

# Restart Server and reconnect at the new port
echo "
The Verber™ server has been made and is ready to run setupverb.

At this point, there is no urgent need to restart the server.
"

# Delete this one-time script
rm /opt/verb/serfs/make-verber
rm /opt/verb/inst/make-verber


