#!/bin/sh
#inkVerbSerf! verb.ink

# This turns off a tld of the verb sites, such as verb.red, but not the other verb.tld sites
## This only works before running setupverb

# How to use:
## ./preverbon [tld]

# Eg:
## ./preverbon kiwi


SITEOFF=$1

sed -i "s/VERB${SITEOFF}=.*/VERB${SITEOFF}=true/g" /var/local/verb/inst/configs/sitetldstatus286

