#!/bin/sh
#inkVerbMaker! verb.ink
## THIS IS THE BIG ONE! THIS INSTALLS THE NAME AND SETS THE SERVER INTO PRODUCTION ##

# This initially sets the server to the specific namespace at verb.ink etc.
## The SSL email is for registering with Letsencrypt.
## Domains are added to the server after this
## This changes the SSH login port, to keep it the same use 22
## This creates a sudo user with login AND a MySQL superuser by the same name and password
## If using the domain mod (make-dommod), the namespace must be your domain.

# How to use:
## ./setupverb [host] [namespace] [tld] [email] [serverIPv4] [serverIPv6 - if none use IPv6NA ] [SSLemail] [php.file-limit] [php.up-size] [php.region] [php.city] [new-port] [new-boss] [boss-pass] [update-repo - optional]
# Elaborate how to use:
## ./setupverb [host - should be namespace or FQDN tld, unless you want to be strange] [inkVerb namespace (purchased) || Domain Mod domain] [FQDN tld, should be 'ink' except multiple servers for namespace] [email server tls, should be 'email' except multiple servers for namespace] [server IP] [SSL email - used for Letsencrypt and the like] [php file upload limit] [php upload size in MB] [php timezone region] [php timezone city] [new port number for ssh/terminal login] [new "boss" sudo user] [boss user password] [verb-update-dev - optional]

# IMPORTANT: Choose a hostname that is: 1. short, 2. unique, 3. memorable, and 4. has only numbers and lower-case letters.
## You will see this name in terminal tabs and window titles when you connect to your Verber via command line.
## Do not choose the same host name on different Verbers of the same namespace, for example ...verb.email and ...verb.ink also need different hosts.
## Consider combining your verb.TLD extension with your Verb namespace
## Eg: joesbigasphalttrucking.verb.ink = joe1ink OR joesbigasphalttrucking.verb.email joeemail

# Timezone list: http://php.net/manual/en/timezones.php
# Common locations:
# Europe Berlin
# Asia Hong_Kong
# Asia Singapore
# America New_York
# America Chicago
# America Phoenix
# America Los_Angeles

# Eg:
## ./setupverb johnny johnny ink email 56.22.108.77 IPv6NA letsencrypt-messages@emaildomain.com 100 1000 Asia Singapore 22 boss bosspassword
## ./setupverb johnny johnny ink email 56.22.108.77 ffff:894:aad8::821 letsencrypt-messages@emaildomain.com 100 1000 Europe Bucharest 867 boss bosspassword
## ./setupverb johnny2 johnny pink rocks 56.22.108.77 IPv6NA letsencrypt-messages@emaildomain.com 100 1000 America New_York 5290 boss bosspassword verb-dev-update
## ./setupverb johnny2 johnny pink rocks 56.22.108.77 ffff:894:aad8::821 letsencrypt-messages@emaildomain.com 100 1000 America Phoenix 5290 boss bosspassword verb-dev-update

### Domain Mod:
## ./setupverb itsme inkisaverb.com ink 56.22.108.77 IPv6 letsencrypt-messages@emaildomain.com 100 1000 America Detroit 22 boss bosspassword
## ./setupverb itsme inkisaverb.com ink 56.22.108.77 ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff letsencrypt-messages@emaildomain.com 100 1000 America Detroit 22 boss bosspassword


## PHP timezone can't use third option of state or country such as America/Argentina/San_Juan or America/Indiana/Knox, only such as America/Chicago
## Get PHP timezone list at: http://php.net/manual/en/timezones.php


HNAME=$1
VNAME=$2
SERVERTLD=$3
SVMAILTLD=$4
SERVERIP=$5
SERVERIPV6=$6
SSLEMAIL=$7
PHPLIMIT=$8
PHPSIZE=$9
PHPREGION=${10}
PHPCITY=${11}
NEWPORT=${12}
NEWBOSS=${13}
NEWBOSSPASS=${14}
VUPREPO=${15}

if [ -z "${15}" ]; then
VUPREPO=verb-update
fi

if [ -z "${14}" ]; then
echo "You must set all variables."
exit 8; fi

# Locale (incase a VPS deleted it after make-verber-preserver)
echo "LANG="en_US.UTF-8"
LANGUAGE="en_US:en"
LC_ALL="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
" > /etc/default/locale

# Snakeoil cert
make-ssl-cert generate-default-snakeoil --force-overwrite

# Use OpenSSL to create a unique Diffie-Helman Group file (security)
rm -f /etc/ssl/private/dhparams.pem
openssl dhparam -out /etc/ssl/private/dhparams.pem 2048
chmod 600 /etc/ssl/private/dhparams.pem

# Site settings
## Configs
cp -R /opt/verb/inst/conf /opt/verb/conf
mv /opt/verb/inst/mysqlrootpassword /opt/verb/conf/
mv /opt/verb/inst/mysqlboss.cnf /opt/verb/conf/
mv /opt/verb/conf/sitenameip286 /opt/verb/conf/sitenameip
mv /opt/verb/conf/siteport286 /opt/verb/conf/siteport
mv /opt/verb/conf/siteinkget286 /opt/verb/conf/siteinkget
mv /opt/verb/conf/sitemailpath286 /opt/verb/conf/sitemailpath
mv /opt/verb/conf/sitetldstatus286 /opt/verb/conf/sitetldstatus
mv /opt/verb/conf/siteinstallstatus286 /opt/verb/conf/siteinstallstatus
## Ensure scripts are executable
chmod 750 /opt/verb/conf/inkcert/*.sh
chmod 750 /opt/verb/conf/inkdns/*.sh
chmod 750 /opt/verb/serfs/*
chmod 750 /opt/verb/donjon/*
chmod 750 /opt/verb/donjon/repoupdate/*
chmod 750 /opt/verb/donjon/wpaddsites/*.wpsh

## Domain Mod?
if [ -f "/opt/verb/inst/domain.mod.conf" ]; then
sed -i "s/name286/\"DOMAIN_MOD-${baseDOM}\"/" /opt/verb/conf/sitenameip
else
sed -i "s/name286/${VNAME}/" /opt/verb/conf/sitenameip
fi

# Site URI List
## domain.mod?
if [ -f "/opt/verb/inst/domain.mod.conf" ]; then
. /opt/verb/inst/domain.mod.conf
echo "#!/bin/sh
## This is a config file for other verb scripts
# Site URI List, whether they are active or not

baseDOM=\"${DMODBASE}\"
nameURI=\"${SERVERTLD}.${DMODBASE}\"
hostURI=\"${HNAME}.${SERVERTLD}.${DMODBASE}\"
serveURI=\"serve.${SERVERTLD}.${DMODBASE}\"
emailTLDURI=\"${SVMAILTLD}.${DMODBASE}\"
emailURI=\"email.${DMODBASE}\"
cityURI=\"city.${DMODBASE}\"
oneURI=\"one.${DMODBASE}\"
inkURI=\"ink.${DMODBASE}\"
blueURI=\"blue.${DMODBASE}\"
vipURI=\"vip.${DMODBASE}\"
kiwiURI=\"kiwi.${DMODBASE}\"
cashURI=\"cash.${DMODBASE}\"
pinkURI=\"pink.${DMODBASE}\"
redURI=\"red.${DMODBASE}\"
rocksURI=\"rocks.${DMODBASE}\"
" > /opt/verb/conf/siteurilist
## Normal verb domains
else
echo "#!/bin/sh
## This is a config file for other verb scripts
# Site URI List, whether they are active or not

nameURI=\"${VNAME}.verb.${SERVERTLD}\"
hostURI=\"${HNAME}.${VNAME}.verb.${SERVERTLD}\"
serveURI=\"serve.${VNAME}.verb.${SERVERTLD}\"
emailTLDURI=\"${VNAME}.verb.${SVMAILTLD}\"
emailURI=\"${VNAME}.verb.email\"
cityURI=\"${VNAME}.verb.city\"
oneURI=\"${VNAME}.verb.one\"
inkURI=\"${VNAME}.verb.ink\"
blueURI=\"${VNAME}.verb.blue\"
vipURI=\"${VNAME}.verb.vip\"
kiwiURI=\"${VNAME}.verb.kiwi\"
cashURI=\"${VNAME}.verb.cash\"
pinkURI=\"${VNAME}.verb.pink\"
redURI=\"${VNAME}.verb.red\"
rocksURI=\"${VNAME}.verb.rocks\"
" > /opt/verb/conf/siteurilist
fi
. /opt/verb/conf/siteurilist

# Site name & IP
serveDIR="$(pwgen -s -1 6)"
sed -i "s/host286/${HNAME}/" /opt/verb/conf/sitenameip
sed -i "s/tld286/${SERVERTLD}/" /opt/verb/conf/sitenameip
sed -i "s/stld286/${SERVERTLD}/" /opt/verb/conf/sitenameip
sed -i "s/servedir286/${serveDIR}/" /opt/verb/conf/sitenameip
sed -i "s/serveuri286/${serveURI}/" /opt/verb/conf/sitenameip
sed -i "s/ip286/${SERVERIP}/" /opt/verb/conf/sitenameip
sed -i "s/ipv6286/${SERVERIPV6}/" /opt/verb/conf/sitenameip
sed -i "s/timeregion286/${PHPREGION}/" /opt/verb/conf/sitenameip
sed -i "s/timecity286/${PHPCITY}/" /opt/verb/conf/sitenameip
sed -i "s/updaterepo286/${VUPREPO}/" /opt/verb/conf/sitenameip
sed -i "s/SITEEMAILTLD=.*/SITEEMAILTLD=\"${SVMAILTLD}\"/" /opt/verb/conf/sitemailpath
sed -i "s/inkcertemail286/${SSLEMAIL}/" /opt/verb/conf/inkcert/inkcertstatus
## Copy other config files with pre-install status
mv /opt/verb/conf/sitemailpass286 /opt/verb/conf/sitemailpass
mv /opt/verb/conf/siteufwip286 /opt/verb/conf/siteufwip

# PHP ini file
mv /opt/verb/conf/php.name286.ini /opt/verb/conf/php.${VNAME}.ini
sed -i "s/phplimit286/${PHPLIMIT}/g" /opt/verb/conf/php.${VNAME}.ini
sed -i "s/phpsize286M/${PHPSIZE}M/g" /opt/verb/conf/php.${VNAME}.ini
sed -i "s/phptimeregion286/${PHPREGION}/g" /opt/verb/conf/php.${VNAME}.ini
sed -i "s/phptimecity286/${PHPCITY}/g" /opt/verb/conf/php.${VNAME}.ini
sed -i "s/name286/${VNAME}/g" /opt/verb/conf/php.${VNAME}.ini
# Get the current PHP version & set php.ini
phpNum=$(/opt/verb/serfs/phpver)
mv /etc/php/${phpNum}/apache2/php.ini /etc/php/${phpNum}/apache2/php.original.ini
ln -sfn /opt/verb/conf/php.${VNAME}.ini /etc/php/${phpNum}/apache2/php.ini

# sites-available
## Directories
chmod -R 750 /opt/verb/conf/site-files/newdomain.tld
chmod -R 750 /opt/verb/conf/site-files/newvipsubdir
chmod -R 750 /opt/verb/conf/site-files/newonesubdir
## Serve URI
/opt/verb/serfs/setserve
## Replace
cp /opt/verb/inst/root-config/etc/apache2/sites-available/* /etc/apache2/sites-available/
sed -i "s/pinkURI286/${pinkURI}/g" /etc/apache2/sites-available/*.conf
sed -i "s/emailURI286/${emailURI}/g" /etc/apache2/sites-available/*.conf
sed -i "s/cityURI286/${cityURI}/g" /etc/apache2/sites-available/*.conf
sed -i "s/oneURI286/${oneURI}/g" /etc/apache2/sites-available/*.conf
sed -i "s/inkURI286/${inkURI}/g" /etc/apache2/sites-available/*.conf
sed -i "s/blueURI286/${blueURI}/g" /etc/apache2/sites-available/*.conf
sed -i "s/vipURI286/${vipURI}/g" /etc/apache2/sites-available/*.conf
sed -i "s/kiwiURI286/${kiwiURI}/g" /etc/apache2/sites-available/*.conf
sed -i "s/cashURI286/${cashURI}/g" /etc/apache2/sites-available/*.conf
sed -i "s/redURI286/${redURI}/g" /etc/apache2/sites-available/*.conf
sed -i "s/rocksURI286/${rocksURI}/g" /etc/apache2/sites-available/*.conf
## Rename
rename "s/pinkURI286/${pinkURI}/" /etc/apache2/sites-available/*.conf
rename "s/emailURI286/${emailURI}/" /etc/apache2/sites-available/*.conf
rename "s/cityURI286/${cityURI}/" /etc/apache2/sites-available/*.conf
rename "s/oneURI286/${oneURI}/" /etc/apache2/sites-available/*.conf
rename "s/inkURI286/${inkURI}/" /etc/apache2/sites-available/*.conf
rename "s/blueURI286/${blueURI}/" /etc/apache2/sites-available/*.conf
rename "s/vipURI286/${vipURI}/" /etc/apache2/sites-available/*.conf
rename "s/kiwiURI286/${kiwiURI}/" /etc/apache2/sites-available/*.conf
rename "s/cashURI286/${cashURI}/" /etc/apache2/sites-available/*.conf
rename "s/redURI286/${redURI}/" /etc/apache2/sites-available/*.conf
rename "s/rocksURI286/${rocksURI}/" /etc/apache2/sites-available/*.conf

# New site-files
## Replace
sed -i "s/pinkURI286/${pinkURI}/g" /opt/verb/conf/site-files/conf/*
sed -i "s/emailURI286/${emailURI}/g" /opt/verb/conf/site-files/conf/*
sed -i "s/cityURI286/${cityURI}/g" /opt/verb/conf/site-files/conf/*
sed -i "s/oneURI286/${oneURI}/g" /opt/verb/conf/site-files/conf/*
sed -i "s/inkURI286/${inkURI}/g" /opt/verb/conf/site-files/conf/*
sed -i "s/blueURI286/${blueURI}/g" /opt/verb/conf/site-files/conf/*
sed -i "s/vipURI286/${vipURI}/g" /opt/verb/conf/site-files/conf/*
sed -i "s/kiwiURI286/${kiwiURI}/g" /opt/verb/conf/site-files/conf/*
sed -i "s/cashURI286/${cashURI}/g" /opt/verb/conf/site-files/conf/*
sed -i "s/redURI286/${redURI}/g" /opt/verb/conf/site-files/conf/*
sed -i "s/rocksURI286/${rocksURI}/g" /opt/verb/conf/site-files/conf/*
## Rename
rename "s/pinkURI286/${pinkURI}/" /opt/verb/conf/site-files/conf/*
rename "s/emailURI286/${emailURI}/" /opt/verb/conf/site-files/conf/*
rename "s/cityURI286/${cityURI}/" /opt/verb/conf/site-files/conf/*
rename "s/oneURI286/${oneURI}/" /opt/verb/conf/site-files/conf/*
rename "s/inkURI286/${inkURI}/" /opt/verb/conf/site-files/conf/*
rename "s/blueURI286/${blueURI}/" /opt/verb/conf/site-files/conf/*
rename "s/vipURI286/${vipURI}/" /opt/verb/conf/site-files/conf/*
rename "s/kiwiURI286/${kiwiURI}/" /opt/verb/conf/site-files/conf/*
rename "s/cashURI286/${cashURI}/" /opt/verb/conf/site-files/conf/*
rename "s/redURI286/${redURI}/" /opt/verb/conf/site-files/conf/*
rename "s/rocksURI286/${rocksURI}/" /opt/verb/conf/site-files/conf/*

# inkCert ini and cron files
## Replace
sed -i "s/pinkURI286/${pinkURI}/g" /opt/verb/conf/inkcert/cli-ini/*
sed -i "s/sslemail286/${SSLEMAIL}/g" /opt/verb/conf/inkcert/cli-ini/*
sed -i "s/nameURI286/${nameURI}/g" /opt/verb/conf/inkcert/verber-openssl.cnf
sed -i "s/emailURI286/${emailURI}/g" /opt/verb/conf/inkcert/cli-ini/*
sed -i "s/cityURI286/${cityURI}/g" /opt/verb/conf/inkcert/cli-ini/*
sed -i "s/oneURI286/${oneURI}/g" /opt/verb/conf/inkcert/cli-ini/*
sed -i "s/inkURI286/${inkURI}/g" /opt/verb/conf/inkcert/cli-ini/*
sed -i "s/blueURI286/${blueURI}/g" /opt/verb/conf/inkcert/cli-ini/*
sed -i "s/vipURI286/${vipURI}/g" /opt/verb/conf/inkcert/cli-ini/*
sed -i "s/kiwiURI286/${kiwiURI}/g" /opt/verb/conf/inkcert/cli-ini/*
sed -i "s/cashURI286/${cashURI}/g" /opt/verb/conf/inkcert/cli-ini/*
sed -i "s/redURI286/${redURI}/g" /opt/verb/conf/inkcert/cli-ini/*
sed -i "s/rocksURI286/${rocksURI}/g" //opt/verb/conf/inkcert/cli-ini/*
## Rename
rename "s/pinkURI286/${pinkURI}/" /opt/verb/conf/inkcert/cli-ini/*
rename "s/emailURI286/${emailURI}/" /opt/verb/conf/inkcert/cli-ini/*
rename "s/cityURI286/${cityURI}/" /opt/verb/conf/inkcert/cli-ini/*
rename "s/oneURI286/${oneURI}/" /opt/verb/conf/inkcert/cli-ini/*
rename "s/inkURI286/${inkURI}/" /opt/verb/conf/inkcert/cli-ini/*
rename "s/blueURI286/${blueURI}/" /opt/verb/conf/inkcert/cli-ini/*
rename "s/vipURI286/${vipURI}/" /opt/verb/conf/inkcert/cli-ini/*
rename "s/kiwiURI286/${kiwiURI}/" /opt/verb/conf/inkcert/cli-ini/*
rename "s/cashURI286/${cashURI}/" /opt/verb/conf/inkcert/cli-ini/*
rename "s/redURI286/${redURI}/" /opt/verb/conf/inkcert/cli-ini/*
rename "s/rocksURI286/${rocksURI}/" /opt/verb/conf/inkcert/cli-ini/*

# www start indexes
/opt/verb/serfs/updatehtmlverbs; wait

# Enable sites
. /opt/verb/conf/sitetldstatus
if [ ${VERBemail}=true ]; then
a2ensite ${emailURI} email.${emailURI}
fi
if [ ${VERBcity}=true ]; then
a2ensite ${cityURI} city.${cityURI} center.${cityURI} console.${cityURI} ctr.${cityURI} cnl.${cityURI}
fi
if [ ${VERBone}=true ]; then
a2ensite ${oneURI} one.${oneURI}
fi
if [ ${VERBink}=true ]; then
a2ensite ${inkURI} ink.${inkURI} ask.${inkURI} bb.${inkURI} blog.${inkURI} code.${inkURI} home.${inkURI} pen.${inkURI} shop.${inkURI} sn.${inkURI} wiki.${inkURI}
fi
if [ ${VERBblue}=true ]; then
a2ensite ${blueURI} blue.${blueURI} caldav.${blueURI} carddav.${blueURI} chat.${blueURI} collabora.${blueURI} dav.${blueURI} nc.${blueURI} owncloud.${blueURI} seafile.${blueURI} webdav.${blueURI} xmpp.${blueURI}
fi
if [ ${VERBvip}=true ]; then
a2ensite ${vipURI} vip.${vipURI} cgi.${vipURI} ftp.${vipURI} files.${vipURI} fossil.${vipURI} ldap.${vipURI} net2ftp.${vipURI} repo.${vipURI} sql.${vipURI}
fi
if [ ${VERBkiwi}=true ]; then
a2ensite ${kiwiURI} kiwi.${kiwiURI} ampache.${kiwiURI} art.${kiwiURI} ejabberd.${kiwiURI} gallery.${kiwiURI} media.${kiwiURI} podcast.${kiwiURI} prosody.${kiwiURI} studio.${kiwiURI} voip.${kiwiURI} webrtc.${kiwiURI}
fi
if [ ${VERBcash}=true ]; then
a2ensite ${cashURI} cash.${cashURI}
fi
if [ ${VERBpink}=true ]; then
a2ensite ${pinkURI} pink.${pinkURI}
fi
if [ ${VERBred}=true ]; then
a2ensite ${redURI} red.${redURI} act.${redURI} crm.${redURI} erp.${redURI} hrm.${redURI} odoo.${redURI} scm.${redURI}
fi
if [ ${VERBrocks}=true ]; then
a2ensite ${rocksURI} rocks.${rocksURI}
fi
systemctl reload apache2

# Create the new boss user
adduser ${NEWBOSS} --gecos ",,," --disabled-password
echo "${NEWBOSS}:${NEWBOSSPASS}" | chpasswd
usermod -a -G sudo ${NEWBOSS}
usermod -a -G www-data ${NEWBOSS}
ln -sfn /opt/verb/boss /home/${NEWBOSS}/
## User privilege specification
echo '# Added in inkVerb preserver setup' >> /etc/sudoers
echo '${NEWBOSS}  ALL=(ALL:ALL) ALL' >> /etc/sudoers

# New Boss MySQL root password
mysql --defaults-extra-file=/opt/verb/conf/mysqlboss.cnf -e "
CREATE USER ${NEWBOSS}@localhost;
SET PASSWORD FOR ${NEWBOSS}@localhost=PASSWORD('${NEWBOSSPASS}');
GRANT ALL PRIVILEGES ON *.* TO '${NEWBOSS}'@'localhost' IDENTIFIED BY '${NEWBOSSPASS}' WITH GRANT OPTION;
FLUSH PRIVILEGES;"

# Host name
hostname ${HNAME}
hostnamectl set-hostname ${HNAME}
##DEV this restart causes an "is masked" error and may not be necessary with the mandatory reboot after setupverb
#systemctl restart hostname
## Set /etc/hostname
echo "${hostURI}" > /etc/hostname
## Set /etc/hosts
sed -i "s/127\.0\.1\.1.*/127\.0\.1\.1 ${hostURI} ${HNAME}\n${SERVERIP} ${hostURI} ${HNAME}/g" /etc/hosts
sed -i "s/127\.0\.0\.1.*/127\.0\.0\.1 localhost.localdomain localhost/g" /etc/hosts
echo "
## inkVerb IPv6 ##
${SERVERIPV6} ${hostURI} ${HNAME}" >> /etc/hosts

# ARPA & inverse IP
/opt/verb/serfs/setip4 ${SITEIP}
/opt/verb/serfs/setip6 ${SITEIPV6}

# Verber DNS records
## Include config
. /opt/verb/conf/sitenameip
## Set the namespace, TLD, and IP values
### db.*
sed -i "s/hostip286/${SITEIP}/g" /opt/verb/conf/inkdns/zones/db.*
sed -i "s/hostip286/${SITEIP}/g" /opt/verb/conf/inkdns/db.*
sed -i "s/hostipv6286/${SITEIPV6}/g" /opt/verb/conf/inkdns/zones/db.*
sed -i "s/hostipv6286/${SITEIPV6}/g" /opt/verb/conf/inkdns/db.*
sed -i "s/sitename286/${SITENAME}/g" /opt/verb/conf/inkdns/zones/db.*
sed -i "s/sitename286/${SITENAME}/g" /opt/verb/conf/inkdns/db.*
sed -i "s/sitetld286/${SITETLD}/g" /opt/verb/conf/inkdns/zones/db.*
sed -i "s/sitetld286/${SITETLD}/g" /opt/verb/conf/inkdns/db.*
sed -i "s/nameURI286/${nameURI}/g" /opt/verb/conf/inkdns/zones/db.*
sed -i "s/nameURI286/${nameURI}/g" /opt/verb/conf/inkdns/db.*
sed -i "s/mailURI286/${hostURI}/g" /opt/verb/conf/inkdns/zones/db.*
sed -i "s/mailURI286/${hostURI}/g" /opt/verb/conf/inkdns/db.*
### nv.*
sed -i "s/hostarpaip286/${SITEARPAIP4}/g" /opt/verb/conf/inkdns/zones/nv.*
sed -i "s/hostarpaip286/${SITEARPAIP4}/g" /opt/verb/conf/inkdns/nv.*
sed -i "s/hostarpaipv6286/${SITEARPAIP6}/g" /opt/verb/conf/inkdns/zones/nv.*
sed -i "s/hostarpaipv6286/${SITEARPAIP6}/g" /opt/verb/conf/inkdns/nv.*
sed -i "s/sitename286/${SITENAME}/g" /opt/verb/conf/inkdns/zones/nv.*
sed -i "s/sitename286/${SITENAME}/g" /opt/verb/conf/inkdns/nv.*
sed -i "s/sitetld286/${SITETLD}/g" /opt/verb/conf/inkdns/zones/nv.*
sed -i "s/sitetld286/${SITETLD}/g" /opt/verb/conf/inkdns/nv.*
sed -i "s/nameURI286/${nameURI}/g" /opt/verb/conf/inkdns/zones/nv.*
sed -i "s/nameURI286/${nameURI}/g" /opt/verb/conf/inkdns/nv.*
sed -i "s/mailURI286/${hostURI}/g" /opt/verb/conf/inkdns/zones/nv.*
sed -i "s/mailURI286/${hostURI}/g" /opt/verb/conf/inkdns/nv.*

## Set the FQDN host
echo "; FQDN Host A Records
${hostURI}.	IN  A		hostip286
${hostURI}.	IN  AAAA	hostipv6286
" >> /opt/verb/conf/inkdns/zones/db.${SITETLD}
## Populate the Verber domains
sed -i "s/hostdomain286/${pinkURI}/g" /opt/verb/conf/inkdns/zones/db.pink
sed -i "s/hostdomain286/${emailURI}/g" /opt/verb/conf/inkdns/zones/db.email
sed -i "s/hostdomain286/${cityURI}/g" /opt/verb/conf/inkdns/zones/db.city
sed -i "s/hostdomain286/${oneURI}/g" /opt/verb/conf/inkdns/zones/db.one
sed -i "s/hostdomain286/${inkURI}/g" /opt/verb/conf/inkdns/zones/db.ink
sed -i "s/hostdomain286/${blueURI}/g" /opt/verb/conf/inkdns/zones/db.blue
sed -i "s/hostdomain286/${vipURI}/g" /opt/verb/conf/inkdns/zones/db.vip
sed -i "s/hostdomain286/${kiwiURI}/g" /opt/verb/conf/inkdns/zones/db.kiwi
sed -i "s/hostdomain286/${cashURI}/g" /opt/verb/conf/inkdns/zones/db.cash
sed -i "s/hostdomain286/${redURI}/g" /opt/verb/conf/inkdns/zones/db.red
sed -i "s/hostdomain286/${rocksURI}/g" /opt/verb/conf/inkdns/zones/db.rocks
sed -i "s/hostdomain286/${pinkURI}/g" /opt/verb/conf/inkdns/zones/nv.pink
sed -i "s/hostdomain286/${emailURI}/g" /opt/verb/conf/inkdns/zones/nv.email
sed -i "s/hostdomain286/${cityURI}/g" /opt/verb/conf/inkdns/zones/nv.city
sed -i "s/hostdomain286/${oneURI}/g" /opt/verb/conf/inkdns/zones/nv.one
sed -i "s/hostdomain286/${inkURI}/g" /opt/verb/conf/inkdns/zones/nv.ink
sed -i "s/hostdomain286/${blueURI}/g" /opt/verb/conf/inkdns/zones/nv.blue
sed -i "s/hostdomain286/${vipURI}/g" /opt/verb/conf/inkdns/zones/nv.vip
sed -i "s/hostdomain286/${kiwiURI}/g" /opt/verb/conf/inkdns/zones/nv.kiwi
sed -i "s/hostdomain286/${cashURI}/g" /opt/verb/conf/inkdns/zones/nv.cash
sed -i "s/hostdomain286/${redURI}/g" /opt/verb/conf/inkdns/zones/nv.red
sed -i "s/hostdomain286/${rocksURI}/g" /opt/verb/conf/inkdns/zones/nv.rocks
## Set the URI names
mv /opt/verb/conf/inkdns/zones/db.pink /opt/verb/conf/inkdns/zones/db.${pinkURI}
mv /opt/verb/conf/inkdns/zones/db.email /opt/verb/conf/inkdns/zones/db.${emailURI}
mv /opt/verb/conf/inkdns/zones/db.city /opt/verb/conf/inkdns/zones/db.${cityURI}
mv /opt/verb/conf/inkdns/zones/db.one /opt/verb/conf/inkdns/zones/db.${oneURI}
mv /opt/verb/conf/inkdns/zones/db.ink /opt/verb/conf/inkdns/zones/db.${inkURI}
mv /opt/verb/conf/inkdns/zones/db.blue /opt/verb/conf/inkdns/zones/db.${blueURI}
mv /opt/verb/conf/inkdns/zones/db.vip /opt/verb/conf/inkdns/zones/db.${vipURI}
mv /opt/verb/conf/inkdns/zones/db.kiwi /opt/verb/conf/inkdns/zones/db.${kiwiURI}
mv /opt/verb/conf/inkdns/zones/db.cash /opt/verb/conf/inkdns/zones/db.${cashURI}
mv /opt/verb/conf/inkdns/zones/db.red /opt/verb/conf/inkdns/zones/db.${redURI}
mv /opt/verb/conf/inkdns/zones/db.rocks /opt/verb/conf/inkdns/zones/db.${rocksURI}
mv /opt/verb/conf/inkdns/zones/nv.pink /opt/verb/conf/inkdns/zones/nv.${pinkURI}
mv /opt/verb/conf/inkdns/zones/nv.email /opt/verb/conf/inkdns/zones/nv.${emailURI}
mv /opt/verb/conf/inkdns/zones/nv.city /opt/verb/conf/inkdns/zones/nv.${cityURI}
mv /opt/verb/conf/inkdns/zones/nv.one /opt/verb/conf/inkdns/zones/nv.${oneURI}
mv /opt/verb/conf/inkdns/zones/nv.ink /opt/verb/conf/inkdns/zones/nv.${inkURI}
mv /opt/verb/conf/inkdns/zones/nv.blue /opt/verb/conf/inkdns/zones/nv.${blueURI}
mv /opt/verb/conf/inkdns/zones/nv.vip /opt/verb/conf/inkdns/zones/nv.${vipURI}
mv /opt/verb/conf/inkdns/zones/nv.kiwi /opt/verb/conf/inkdns/zones/nv.${kiwiURI}
mv /opt/verb/conf/inkdns/zones/nv.cash /opt/verb/conf/inkdns/zones/nv.${cashURI}
mv /opt/verb/conf/inkdns/zones/nv.red /opt/verb/conf/inkdns/zones/nv.${redURI}
mv /opt/verb/conf/inkdns/zones/nv.rocks /opt/verb/conf/inkdns/zones/nv.${rocksURI}
## Serial Nos
cd /opt/verb/conf/inkdns/zones
for inkZoneDB in db.*; do
inkZone="$(echo ${inkZoneDB} | sed 's/db\.//' )"
/opt/verb/serfs/inkdnsserial ${inkZone}
done

# Firewall
apt install -y ufw
## Set for IPV6 (should be set already, but just to be sure)
sed -i "s/IPV6=.*/IPV6=yes/g" /etc/default/ufw
## Port (set to something to avoid attacks)
sed -i "/Port.*/ c\Port ${NEWPORT}" /etc/ssh/sshd_config
ufw allow ${NEWPORT}
sed -i "/SITEPORT.*/ c\SITEPORT=${NEWPORT}" /opt/verb/conf/siteport
## Reset settings
ufw allow ssh
ufw allow http
ufw allow https
ufw allow ftp

# File permissions for configs
chmod 660 -R /opt/verb/conf

# Instructions
######################### FIX inkCert instructions #########################
echo "After 1. setting up any extra domains and subdomains, 2. turning off any unused verb domains and changing the email server setting if you choose,"
## Domain Mod?
if grep -Fq "SITENAME=DOMAIN_MOD-" /opt/verb/conf/sitenameip; then
echo "- Run for Letsencrypt: inkcertdole-all-verbs (or inkcertdole ${nameURI} if not using a single server)"
else
echo "- Run for Letsencrypt: inkcertdole-all-verbs (or inkcertdole ${nameURI} if not using a single server)"
fi
## Common message
echo "- Then, set up email with postfix and roundcube.

If you choose to set up email before doinkcert, you will need to make an Advanced > exception rule for these in your browser concerning security/safety/SSL, you should not need to permanently store it.

You should reboot the server now using:

reboot

Then, for SSH,

login using: 'ssh root@${SERVERIP} -p ${NEWPORT}'

OR for password with the new boss user,

login using: 'ssh ${NEWBOSS}@${SERVERIP} -p ${NEWPORT}'
"

# Cleanup
rm -f /opt/verb/serfs/setupverb
rm -f /opt/verb/inst/setupverb
rm -f /opt/verb/inst/preverboff
rm -f /opt/verb/inst/preverbon
rm -f /opt/verb/inst/make-dommod
ufw --force enable
systemctl restart sshd
