#!/bin/sh
## This is a config file for other verb scripts

SITENAME="name286"
SITEHOST="host286"
SITETLD="tld286"
SITEIP="ip286"
SITEIPV6="ipv6286"
SITETIMEREGION="timeregion286"
SITETIMECITY="timecity286"
SITEUPDATEREPO="updaterepo286"

